"""initial

Revision ID: a830ed5ce83a
Revises: 
Create Date: 2026-03-25 16:04:26.944175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a830ed5ce83a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('freeze_time', sa.Integer(), nullable=True),
    sa.Column('scoring_rule', postgresql.ENUM('IOI', 'ACM', name='scoring_rule'), nullable=False),
    sa.Column('visibility', postgresql.ENUM('PUBLIC', 'PRIVATE', 'CONTEST_ONLY', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_contests_end_time', 'contests', ['end_time'], unique=False)
    op.create_index('ix_contests_slug', 'contests', ['slug'], unique=False)
    op.create_index('ix_contests_start_time', 'contests', ['start_time'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('visibility', postgresql.ENUM('PUBLIC', 'PRIVATE', 'CONTEST_ONLY', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_problems_difficulty', 'problems', ['difficulty'], unique=False)
    op.create_index('ix_problems_slug', 'problems', ['slug'], unique=False)
    op.create_index('ix_problems_visibility', 'problems', ['visibility'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', 'GUEST', name='role'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verify_token', sa.String(), nullable=True),
    sa.Column('email_verify_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_verify_token'),
    sa.UniqueConstraint('password_reset_token'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('contest_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contest_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'user_id', name='uq_contest_participant')
    )
    op.create_index('ix_contest_participants_contest_id', 'contest_participants', ['contest_id'], unique=False)
    op.create_index('ix_contest_participants_user_id', 'contest_participants', ['user_id'], unique=False)
    op.create_table('contest_problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contest_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'problem_id', name='uq_contest_problem')
    )
    op.create_index('ix_contest_problems_contest_id', 'contest_problems', ['contest_id'], unique=False)
    op.create_index('ix_contest_problems_problem_id', 'contest_problems', ['problem_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('contest_id', sa.UUID(), nullable=True),
    sa.Column('language', postgresql.ENUM('C', 'CPP', 'PYTHON', 'JAVA', name='language'), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'COMPILING', 'RUNNING', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILATION_ERROR', name='submission_status'), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('memory_used', sa.Integer(), nullable=True),
    sa.Column('compilation_error', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contest_relative_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_contest_id', 'submissions', ['contest_id'], unique=False)
    op.create_index('ix_submissions_problem_id', 'submissions', ['problem_id'], unique=False)
    op.create_index('ix_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('ix_submissions_submitted_at', 'submissions', ['submitted_at'], unique=False)
    op.create_index('ix_submissions_user_id', 'submissions', ['user_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('input_file', sa.Text(), nullable=False),
    sa.Column('output_file', sa.Text(), nullable=False),
    sa.Column('input_checksum', sa.String(), nullable=False),
    sa.Column('output_checksum', sa.String(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_cases_problem_id', 'test_cases', ['problem_id'], unique=False)
    op.create_index('ix_test_cases_problem_order', 'test_cases', ['problem_id', 'order_index'], unique=False)
    op.create_table('test_case_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'COMPILING', 'RUNNING', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILATION_ERROR', name='submission_status'), nullable=False),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('memory_used', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_case_results_submission_id', 'test_case_results', ['submission_id'], unique=False)
    op.create_index('ix_test_case_results_test_case_id', 'test_case_results', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_case_results_test_case_id', table_name='test_case_results')
    op.drop_index('ix_test_case_results_submission_id', table_name='test_case_results')
    op.drop_table('test_case_results')
    op.drop_index('ix_test_cases_problem_order', table_name='test_cases')
    op.drop_index('ix_test_cases_problem_id', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index('ix_submissions_user_id', table_name='submissions')
    op.drop_index('ix_submissions_submitted_at', table_name='submissions')
    op.drop_index('ix_submissions_status', table_name='submissions')
    op.drop_index('ix_submissions_problem_id', table_name='submissions')
    op.drop_index('ix_submissions_contest_id', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_contest_problems_problem_id', table_name='contest_problems')
    op.drop_index('ix_contest_problems_contest_id', table_name='contest_problems')
    op.drop_table('contest_problems')
    op.drop_index('ix_contest_participants_user_id', table_name='contest_participants')
    op.drop_index('ix_contest_participants_contest_id', table_name='contest_participants')
    op.drop_table('contest_participants')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_problems_visibility', table_name='problems')
    op.drop_index('ix_problems_slug', table_name='problems')
    op.drop_index('ix_problems_difficulty', table_name='problems')
    op.drop_table('problems')
    op.drop_index('ix_contests_start_time', table_name='contests')
    op.drop_index('ix_contests_slug', table_name='contests')
    op.drop_index('ix_contests_end_time', table_name='contests')
    op.drop_table('contests')
    # ### end Alembic commands ###
